### DISCUSSION TITLE
How to support more than 256 fields

### DISCUSSION THREAD

**Discussion by qicosmos** [qicosmos/iguana#346] [General]
see doc:https://alibaba.github.io/yalantinglibs/zh/struct_pack/struct_pack_tips.html#%E5%A6%82%E4%BD%95%E6%89%A9%E5%B1%95%E7%BB%93%E6%9E%84%E4%BD%93%E5%AD%97%E6%AE%B5%E4%B8%8A%E9%99%90

**Comment by jdx** [comment]
*Note: This reply is AI-generated.*

Yes, mise now has environment caching that can help with this use case! You can enable it with:

```toml
# ~/.config/mise/config.toml
[settings]
env_cache = true
env_cache_ttl = "1h"  # optional, default is 1h
```

When enabled, mise caches the computed environment to disk (encrypted with a session-scoped key). The cache is automatically invalidated when config files change, tool versions change, or the TTL expires.

For env plugins like `mise-env-fnox`, they can declare themselves cacheable by returning `{cacheable = true, watch_files = [...]}` from their `MiseEnv` hook, which allows mise to cache their output and only re-fetch when watched files change.

I've also submitted a PR to update the docs to reflect this: https://github.com/jdx/mise/pull/7849
